/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.samklr.avro.messages;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MtmMessageKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -516692796011238904L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MtmMessageKey\",\"namespace\":\"com.samklr.avro.messages\",\"fields\":[{\"name\":\"jobId\",\"type\":\"string\"},{\"name\":\"sc\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence jobId;
  @Deprecated public long sc;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MtmMessageKey() {}

  /**
   * All-args constructor.
   * @param jobId The new value for jobId
   * @param sc The new value for sc
   */
  public MtmMessageKey(java.lang.CharSequence jobId, java.lang.Long sc) {
    this.jobId = jobId;
    this.sc = sc;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return jobId;
    case 1: return sc;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: jobId = (java.lang.CharSequence)value$; break;
    case 1: sc = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'jobId' field.
   * @return The value of the 'jobId' field.
   */
  public java.lang.CharSequence getJobId() {
    return jobId;
  }

  /**
   * Sets the value of the 'jobId' field.
   * @param value the value to set.
   */
  public void setJobId(java.lang.CharSequence value) {
    this.jobId = value;
  }

  /**
   * Gets the value of the 'sc' field.
   * @return The value of the 'sc' field.
   */
  public java.lang.Long getSc() {
    return sc;
  }

  /**
   * Sets the value of the 'sc' field.
   * @param value the value to set.
   */
  public void setSc(java.lang.Long value) {
    this.sc = value;
  }

  /**
   * Creates a new MtmMessageKey RecordBuilder.
   * @return A new MtmMessageKey RecordBuilder
   */
  public static com.samklr.avro.messages.MtmMessageKey.Builder newBuilder() {
    return new com.samklr.avro.messages.MtmMessageKey.Builder();
  }

  /**
   * Creates a new MtmMessageKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MtmMessageKey RecordBuilder
   */
  public static com.samklr.avro.messages.MtmMessageKey.Builder newBuilder(com.samklr.avro.messages.MtmMessageKey.Builder other) {
    return new com.samklr.avro.messages.MtmMessageKey.Builder(other);
  }

  /**
   * Creates a new MtmMessageKey RecordBuilder by copying an existing MtmMessageKey instance.
   * @param other The existing instance to copy.
   * @return A new MtmMessageKey RecordBuilder
   */
  public static com.samklr.avro.messages.MtmMessageKey.Builder newBuilder(com.samklr.avro.messages.MtmMessageKey other) {
    return new com.samklr.avro.messages.MtmMessageKey.Builder(other);
  }

  /**
   * RecordBuilder for MtmMessageKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MtmMessageKey>
    implements org.apache.avro.data.RecordBuilder<MtmMessageKey> {

    private java.lang.CharSequence jobId;
    private long sc;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.samklr.avro.messages.MtmMessageKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.jobId)) {
        this.jobId = data().deepCopy(fields()[0].schema(), other.jobId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sc)) {
        this.sc = data().deepCopy(fields()[1].schema(), other.sc);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MtmMessageKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.samklr.avro.messages.MtmMessageKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.jobId)) {
        this.jobId = data().deepCopy(fields()[0].schema(), other.jobId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sc)) {
        this.sc = data().deepCopy(fields()[1].schema(), other.sc);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'jobId' field.
      * @return The value.
      */
    public java.lang.CharSequence getJobId() {
      return jobId;
    }

    /**
      * Sets the value of the 'jobId' field.
      * @param value The value of 'jobId'.
      * @return This builder.
      */
    public com.samklr.avro.messages.MtmMessageKey.Builder setJobId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.jobId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'jobId' field has been set.
      * @return True if the 'jobId' field has been set, false otherwise.
      */
    public boolean hasJobId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'jobId' field.
      * @return This builder.
      */
    public com.samklr.avro.messages.MtmMessageKey.Builder clearJobId() {
      jobId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sc' field.
      * @return The value.
      */
    public java.lang.Long getSc() {
      return sc;
    }

    /**
      * Sets the value of the 'sc' field.
      * @param value The value of 'sc'.
      * @return This builder.
      */
    public com.samklr.avro.messages.MtmMessageKey.Builder setSc(long value) {
      validate(fields()[1], value);
      this.sc = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sc' field has been set.
      * @return True if the 'sc' field has been set, false otherwise.
      */
    public boolean hasSc() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sc' field.
      * @return This builder.
      */
    public com.samklr.avro.messages.MtmMessageKey.Builder clearSc() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public MtmMessageKey build() {
      try {
        MtmMessageKey record = new MtmMessageKey();
        record.jobId = fieldSetFlags()[0] ? this.jobId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.sc = fieldSetFlags()[1] ? this.sc : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
