/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.samklr.avro.messages;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MtmMessageValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8491441781065694434L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MtmMessageValue\",\"namespace\":\"com.samklr.avro.messages\",\"fields\":[{\"name\":\"date\",\"type\":\"int\"},{\"name\":\"mtms\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int date;
  @Deprecated public java.util.List<java.lang.Double> mtms;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MtmMessageValue() {}

  /**
   * All-args constructor.
   * @param date The new value for date
   * @param mtms The new value for mtms
   */
  public MtmMessageValue(java.lang.Integer date, java.util.List<java.lang.Double> mtms) {
    this.date = date;
    this.mtms = mtms;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return date;
    case 1: return mtms;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: date = (java.lang.Integer)value$; break;
    case 1: mtms = (java.util.List<java.lang.Double>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.Integer getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.Integer value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'mtms' field.
   * @return The value of the 'mtms' field.
   */
  public java.util.List<java.lang.Double> getMtms() {
    return mtms;
  }

  /**
   * Sets the value of the 'mtms' field.
   * @param value the value to set.
   */
  public void setMtms(java.util.List<java.lang.Double> value) {
    this.mtms = value;
  }

  /**
   * Creates a new MtmMessageValue RecordBuilder.
   * @return A new MtmMessageValue RecordBuilder
   */
  public static com.samklr.avro.messages.MtmMessageValue.Builder newBuilder() {
    return new com.samklr.avro.messages.MtmMessageValue.Builder();
  }

  /**
   * Creates a new MtmMessageValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MtmMessageValue RecordBuilder
   */
  public static com.samklr.avro.messages.MtmMessageValue.Builder newBuilder(com.samklr.avro.messages.MtmMessageValue.Builder other) {
    return new com.samklr.avro.messages.MtmMessageValue.Builder(other);
  }

  /**
   * Creates a new MtmMessageValue RecordBuilder by copying an existing MtmMessageValue instance.
   * @param other The existing instance to copy.
   * @return A new MtmMessageValue RecordBuilder
   */
  public static com.samklr.avro.messages.MtmMessageValue.Builder newBuilder(com.samklr.avro.messages.MtmMessageValue other) {
    return new com.samklr.avro.messages.MtmMessageValue.Builder(other);
  }

  /**
   * RecordBuilder for MtmMessageValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MtmMessageValue>
    implements org.apache.avro.data.RecordBuilder<MtmMessageValue> {

    private int date;
    private java.util.List<java.lang.Double> mtms;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.samklr.avro.messages.MtmMessageValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.date)) {
        this.date = data().deepCopy(fields()[0].schema(), other.date);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.mtms)) {
        this.mtms = data().deepCopy(fields()[1].schema(), other.mtms);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MtmMessageValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.samklr.avro.messages.MtmMessageValue other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.date)) {
        this.date = data().deepCopy(fields()[0].schema(), other.date);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.mtms)) {
        this.mtms = data().deepCopy(fields()[1].schema(), other.mtms);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.Integer getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.samklr.avro.messages.MtmMessageValue.Builder setDate(int value) {
      validate(fields()[0], value);
      this.date = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.samklr.avro.messages.MtmMessageValue.Builder clearDate() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'mtms' field.
      * @return The value.
      */
    public java.util.List<java.lang.Double> getMtms() {
      return mtms;
    }

    /**
      * Sets the value of the 'mtms' field.
      * @param value The value of 'mtms'.
      * @return This builder.
      */
    public com.samklr.avro.messages.MtmMessageValue.Builder setMtms(java.util.List<java.lang.Double> value) {
      validate(fields()[1], value);
      this.mtms = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'mtms' field has been set.
      * @return True if the 'mtms' field has been set, false otherwise.
      */
    public boolean hasMtms() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'mtms' field.
      * @return This builder.
      */
    public com.samklr.avro.messages.MtmMessageValue.Builder clearMtms() {
      mtms = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public MtmMessageValue build() {
      try {
        MtmMessageValue record = new MtmMessageValue();
        record.date = fieldSetFlags()[0] ? this.date : (java.lang.Integer) defaultValue(fields()[0]);
        record.mtms = fieldSetFlags()[1] ? this.mtms : (java.util.List<java.lang.Double>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
